### ISSUE TITLE
INSERT SELECT Statement

### ISSUE THREAD

**Issue by yapnel** [bedorlan/priscilla#5]
Hi

It seems to throw error for a pl/sql stored procedure that has INSERT SELECT statement.
Is this feature supported?

Thanks

python3.6 lib/S2S.py /opt/priscilla/input/wlk_rec_mi_hedgei_bak.pkg /opt/priscilla/output/wlk_rec_mi_hedgei_bak.py
Traceback (most recent call last):
  File "lib/S2S.py", line 37, in <module>
    main(sys.argv)
  File "lib/S2S.py", line 23, in main
    node = tree.accept(visitor)
  File "./built/PlSqlParser.py", line 7324, in accept
    return visitor.visitSql_script(self)
  File "/opt/priscilla/lib/ScriptVisitor.py", line 43, in visitSql_script
    body = self.visitChildren(ctx)
  File "/usr/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "./built/PlSqlParser.py", line 7541, in accept
    return visitor.visitUnit_statement(self)
  File "/opt/priscilla/lib/ScriptVisitor.py", line 52, in visitUnit_statement
    ret = self.visitChildren(ctx)
  File "/usr/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "./built/PlSqlParser.py", line 10058, in accept
    return visitor.visitCreate_procedure_body(self)
  File "/opt/priscilla/lib/ScriptVisitor.py", line 106, in visitCreate_procedure_body
    return self.visitCreate_function_body(ctx)
  File "/opt/priscilla/lib/ScriptVisitor.py", line 112, in visitCreate_function_body
    ret = visitor.visitChildren(ctx)
  File "/usr/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "./built/PlSqlParser.py", line 36221, in accept
    return visitor.visitBody(self)
  File "/opt/priscilla/lib/ScriptVisitor.py", line 220, in visitBody
    ret = self.visitChildren(ctx)
  File "/usr/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "./built/PlSqlParser.py", line 34570, in accept
    return visitor.visitSeq_of_statements(self)
  File "./built/PlSqlParserVisitor.py", line 1394, in visitSeq_of_statements
    return self.visitChildren(ctx)
  File "/usr/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "./built/PlSqlParser.py", line 34757, in accept
    return visitor.visitStatement(self)
  File "/opt/priscilla/lib/ScriptVisitor.py", line 286, in visitStatement
    ret = self.visitChildren(ctx)
  File "/usr/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "./built/PlSqlParser.py", line 36524, in accept
    return visitor.visitSql_statement(self)
  File "./built/PlSqlParserVisitor.py", line 1529, in visitSql_statement
    return self.visitChildren(ctx)
  File "/usr/lib/python3.6/site-packages/antlr4/tree/Tree.py", line 44, in visitChildren
    childResult = c.accept(self)
  File "./built/PlSqlParser.py", line 36757, in accept
    return visitor.visitData_manipulation_language_statements(self)
  File "/opt/priscilla/lib/ScriptVisitor.py", line 534, in visitData_manipulation_language_statements
    return visitor.visitData_manipulation_language_statements(ctx)
  File "/opt/priscilla/lib/SqlVisitor.py", line 16, in visitData_manipulation_language_statements
    ret = self.visitSelect_statement(ctx)
  File "/opt/priscilla/lib/SqlVisitor.py", line 41, in visitSelect_statement
    param.start_index -= ctx.start.start
AttributeError: 'SQL' object has no attribute 'start_index'

**Comment by bedorlan** [comment]
Hi. Can you provide me with some test code please?

**Comment by yapnel** [comment]
CREATE OR REPLACE PROCEDURE TEST1
AS
BEGIN
   INSERT INTO WH_F WT (BUSINESS_DATE, AMOUNT)
      (  SELECT BUSINESS_DATE, SUM (PL) AS AMOUNT
           FROM WH_LOAN_F
       GROUP BY BUSINESS_DATE);

   COMMIT;
END TEST1;
/


CREATE OR REPLACE PROCEDURE TEST2
AS
   V_HIER_START   DATE;
BEGIN
   SELECT HIER_START
     INTO V_HIER_START
     FROM CIN_BUILD_LOG CBL
    WHERE CBL.BUSINESS_DATE = V_VERDATE;

   COMMIT;
END TEST2;
/


CREATE OR REPLACE PROCEDURE TEST3
AS
BEGIN
   MERGE INTO member_staging x
        USING (SELECT member_id,
                      first_name,
                      last_name,
                      RANK
                 FROM members) y
           ON (x.member_id = y.member_id)
   WHEN MATCHED
   THEN
      UPDATE SET
         x.first_name = y.first_name,
         x.last_name = y.last_name,
         x.RANK = y.RANK
              WHERE    x.first_name <> y.first_name
                    OR x.last_name <> y.last_name
                    OR x.RANK <> y.RANK
   WHEN NOT MATCHED
   THEN
      INSERT            (x.member_id,
                         x.first_name,
                         x.last_name,
                         x.RANK)
          VALUES (y.member_id,
                  y.first_name,
                  y.last_name,
                  y.RANK);

   COMMIT;
END TEST3;
/
